// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// ProductsPage renders the products management page
func ProductsPage() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"page-header\"><div><h1 class=\"page-title\">Productos</h1><p class=\"page-sub\" id=\"total-products\">Cargando...</p></div><button class=\"btn btn-primary\" id=\"btn-new-product\"><svg width=\"16\" height=\"16\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" viewBox=\"0 0 24 24\"><line x1=\"12\" y1=\"5\" x2=\"12\" y2=\"19\"></line><line x1=\"5\" y1=\"12\" x2=\"19\" y2=\"12\"></line></svg> Nuevo Producto</button></div><!-- Toolbar --><div class=\"toolbar\"><input type=\"text\" class=\"form-input\" placeholder=\"Buscar por nombre, SKU...\" id=\"search-input\"> <select id=\"filter-status\" class=\"form-select\"><option value=\"\">Todos</option> <option value=\"activo\">Activo</option> <option value=\"inactivo\">Inactivo</option></select> <select id=\"filter-category\" class=\"form-select\"><option value=\"\">Todas las categorías</option></select></div><!-- Products Table --><div class=\"card\"><div class=\"card-body p-0\"><table><thead><tr><th>Producto</th><th>Categoría</th><th>Precio</th><th>Stock</th><th>Variantes</th><th>Fotos</th><th>Estado</th><th>Acciones</th></tr></thead> <tbody id=\"products-tbody\"><tr><td colspan=\"8\" style=\"text-align:center;padding:40px;color:var(--text-mut)\">Cargando...</td></tr></tbody></table></div></div><div class=\"pagination\" id=\"pagination\"></div><!-- Modal is built dynamically by products.js --><script src=\"/static/js/toast.js\"></script><script src=\"/static/js/products.js\"></script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
